import type {
  Generator,
  GeneratorContext,
  GeneratorOutput,
  FabricSchema,
  EntitySchema,
  FieldSchema,
} from '@quoin/core'

interface JsonSchemaProperty {
  type?: string | string[]
  format?: string
  enum?: string[]
  description?: string
  items?: JsonSchemaProperty
  $ref?: string
}

interface JsonSchema {
  $schema: string
  $id: string
  title: string
  description?: string
  type: 'object'
  required?: string[]
  properties: Record<string, JsonSchemaProperty>
  additionalProperties: false
}

function fieldToJsonSchema(field: FieldSchema): JsonSchemaProperty {
  const prop: JsonSchemaProperty = {}
  if (field.description) prop.description = field.description

  if (field.type === 'enum' && field.enumValues) {
    prop.type = 'string'
    prop.enum = field.enumValues
    return prop
  }

  const mapping: Record<string, JsonSchemaProperty> = {
    string:    { type: 'string' },
    number:    { type: 'number' },
    integer:   { type: 'integer' },
    decimal:   { type: 'number' },
    boolean:   { type: 'boolean' },
    uuid:      { type: 'string', format: 'uuid' },
    timestamp: { type: 'string', format: 'date-time' },
    date:      { type: 'string', format: 'date' },
    email:     { type: 'string', format: 'email' },
    url:       { type: 'string', format: 'uri' },
    json:      {},
  }

  const m = mapping[field.type]
  if (m) {
    if (m.type) prop.type = m.type
    if (m.format) prop.format = m.format
  }

  if (field.nullable) {
    prop.type = prop.type ? [prop.type as string, 'null'] : ['null']
  }

  return prop
}

function buildEntityJsonSchema(namespace: string, entity: EntitySchema): JsonSchema {
  const required: string[] = []
  const properties: Record<string, JsonSchemaProperty> = {}

  for (const field of Object.values(entity.fields)) {
    if (!field.nullable) required.push(field.name)
    properties[field.name] = fieldToJsonSchema(field)
  }

  const schema: JsonSchema = {
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: `${namespace}${entity.name}`,
    title: entity.name,
    type: 'object',
    properties,
    additionalProperties: false,
  }

  if (entity.description) schema.description = entity.description
  if (required.length) schema.required = required

  return schema
}

export class JsonSchemaGenerator implements Generator {
  readonly name = 'jsonschema'
  readonly dependsOn: string[] = []

  async generate(schema: FabricSchema, _ctx: GeneratorContext): Promise<GeneratorOutput> {
    const namespace = schema.meta.namespace ?? `https://schema.org/${schema.meta.name}/`
    const header = '// @generated by @quoin/generator-jsonschema — do not edit\n'
    const files: GeneratorOutput['files'] = []

    for (const entity of Object.values(schema.entities)) {
      const jsonSchema = buildEntityJsonSchema(namespace, entity)
      files.push({
        path: `jsonschema/${entity.name}.schema.json`,
        content: JSON.stringify(jsonSchema, null, 2) + '\n',
        header,
      })
    }

    return { files }
  }
}
