import * as os from 'os'
import * as fs from 'fs'
import * as path from 'path'
import { runGenerators } from './runner'
import type { Generator, GeneratorContext, GeneratorOutput } from './types'
import type { FabricSchema } from '../ir/types'
import { SNAPSHOT_FILE } from './snapshot'

const minimalSchema: FabricSchema = {
  version: '2.0.0',
  meta: { name: 'test' },
  entities: {},
  apis: {},
}

function makeStubGen(name: string, dependsOn: string[] = []): Generator {
  return {
    name,
    dependsOn,
    async generate(_schema: FabricSchema, _ctx: GeneratorContext): Promise<GeneratorOutput> {
      return {
        files: [{ path: `${name}/output.txt`, content: `generated by ${name}` }],
        artifacts: { [name]: true },
      }
    },
  }
}

describe('runGenerators', () => {
  let tmpDir: string

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'newel-test-'))
  })

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  it('writes generated files to disk', async () => {
    const gen = makeStubGen('stub')
    await runGenerators(minimalSchema, [gen], { outputDir: tmpDir })
    const filePath = path.join(tmpDir, 'stub/output.txt')
    expect(fs.existsSync(filePath)).toBe(true)
    expect(fs.readFileSync(filePath, 'utf-8')).toContain('generated by stub')
  })

  it('writes manifest', async () => {
    const gen = makeStubGen('stub')
    const result = await runGenerators(minimalSchema, [gen], { outputDir: tmpDir })
    expect(result.manifest.files).toHaveLength(1)
    expect(result.manifest.files[0].generator).toBe('stub')
    const manifestPath = path.join(tmpDir, 'newel.manifest.json')
    expect(fs.existsSync(manifestPath)).toBe(true)
  })

  it('threads outputs between generators', async () => {
    let upstreamSeen = false
    const upstream = makeStubGen('upstream')
    const downstream: Generator = {
      name: 'downstream',
      dependsOn: ['upstream'],
      async generate(_s, ctx) {
        upstreamSeen = ctx.outputs.has('upstream')
        return { files: [] }
      },
    }
    await runGenerators(minimalSchema, [downstream, upstream], { outputDir: tmpDir })
    expect(upstreamSeen).toBe(true)
  })

  it('dryRun does not write files', async () => {
    const gen = makeStubGen('stub')
    await runGenerators(minimalSchema, [gen], { outputDir: tmpDir, dryRun: true })
    expect(fs.existsSync(path.join(tmpDir, 'stub/output.txt'))).toBe(false)
  })

  it('writes IR snapshot to disk', async () => {
    const gen = makeStubGen('stub')
    await runGenerators(minimalSchema, [gen], { outputDir: tmpDir })
    const snapshotPath = path.join(tmpDir, SNAPSHOT_FILE)
    expect(fs.existsSync(snapshotPath)).toBe(true)
    const snapshot = JSON.parse(fs.readFileSync(snapshotPath, 'utf-8'))
    expect(snapshot.schemaHash).toMatch(/^sha256:/)
    expect(snapshot.schema).toEqual(minimalSchema)
    expect(snapshot.generatedAt).toBeDefined()
  })

  it('dryRun does not write IR snapshot', async () => {
    const gen = makeStubGen('stub')
    await runGenerators(minimalSchema, [gen], { outputDir: tmpDir, dryRun: true })
    expect(fs.existsSync(path.join(tmpDir, SNAPSHOT_FILE))).toBe(false)
  })

  it('exposes previousSnapshot=null on first run', async () => {
    const gen = makeStubGen('stub')
    const result = await runGenerators(minimalSchema, [gen], { outputDir: tmpDir })
    expect(result.previousSnapshot).toBeNull()
  })

  it('exposes previousSnapshot on subsequent runs', async () => {
    const gen = makeStubGen('stub')
    await runGenerators(minimalSchema, [gen], { outputDir: tmpDir })

    let capturedPreviousSnapshot: unknown = undefined
    const snapshotCapture: Generator = {
      name: 'capture',
      dependsOn: [],
      async generate(_schema, ctx) {
        capturedPreviousSnapshot = ctx.previousSnapshot
        return { files: [] }
      },
    }
    await runGenerators(minimalSchema, [snapshotCapture], { outputDir: tmpDir })
    expect(capturedPreviousSnapshot).not.toBeNull()
    expect((capturedPreviousSnapshot as { schema: FabricSchema }).schema).toEqual(minimalSchema)
  })

  it('returns snapshot in RunResult', async () => {
    const gen = makeStubGen('stub')
    const result = await runGenerators(minimalSchema, [gen], { outputDir: tmpDir })
    expect(result.snapshot.schema).toEqual(minimalSchema)
    expect(result.snapshot.schemaHash).toMatch(/^sha256:/)
  })

  describe('patches', () => {
    const schemaWithEntity: FabricSchema = {
      ...minimalSchema,
      entities: {
        Book: {
          name: 'Book',
          role: 'entity',
          description: 'original',
          fields: {},
          relations: {},
          behaviors: {},
          pii: [],
          gdpr: {},
        },
      },
    }

    it('applies merge patches before generators see the schema', async () => {
      let seenDescription: string | undefined
      const gen: Generator = {
        name: 'observer',
        dependsOn: [],
        async generate(schema) {
          seenDescription = schema.entities.Book?.description
          return { files: [] }
        },
      }
      await runGenerators(schemaWithEntity, [gen], {
        outputDir: tmpDir,
        patches: [{ op: 'merge', target: 'entity.Book', value: { description: 'patched' } }],
      })
      expect(seenDescription).toBe('patched')
    })

    it('snapshot stores the patched schema', async () => {
      const gen = makeStubGen('stub')
      const result = await runGenerators(schemaWithEntity, [gen], {
        outputDir: tmpDir,
        patches: [{ op: 'merge', target: 'entity.Book', value: { description: 'patched' } }],
      })
      expect(result.snapshot.schema.entities.Book.description).toBe('patched')
    })

    it('suppresses files matching a pattern', async () => {
      const gen = makeStubGen('stub')
      const result = await runGenerators(minimalSchema, [gen], {
        outputDir: tmpDir,
        patches: [{ op: 'suppress', pattern: 'stub/output.txt' }],
      })
      expect(fs.existsSync(path.join(tmpDir, 'stub/output.txt'))).toBe(false)
      expect(result.suppressedFiles).toEqual(['stub/output.txt'])
    })

    it('suppresses files matching a wildcard pattern', async () => {
      const gen: Generator = {
        name: 'multi',
        dependsOn: [],
        async generate() {
          return {
            files: [
              { path: 'multi/a.sql', content: 'a' },
              { path: 'multi/b.sql', content: 'b' },
              { path: 'multi/index.ts', content: 'ts' },
            ],
          }
        },
      }
      const result = await runGenerators(minimalSchema, [gen], {
        outputDir: tmpDir,
        patches: [{ op: 'suppress', pattern: 'multi/*.sql' }],
      })
      expect(fs.existsSync(path.join(tmpDir, 'multi/a.sql'))).toBe(false)
      expect(fs.existsSync(path.join(tmpDir, 'multi/b.sql'))).toBe(false)
      expect(fs.existsSync(path.join(tmpDir, 'multi/index.ts'))).toBe(true)
      expect(result.suppressedFiles).toEqual(['multi/a.sql', 'multi/b.sql'])
    })

    it('suppressed files are not added to the manifest', async () => {
      const gen = makeStubGen('stub')
      const result = await runGenerators(minimalSchema, [gen], {
        outputDir: tmpDir,
        patches: [{ op: 'suppress', pattern: 'stub/output.txt' }],
      })
      expect(result.manifest.files).toHaveLength(0)
    })

    it('returns empty suppressedFiles when no patches', async () => {
      const gen = makeStubGen('stub')
      const result = await runGenerators(minimalSchema, [gen], { outputDir: tmpDir })
      expect(result.suppressedFiles).toEqual([])
    })
  })
})
